#import "V2Server.h"

#import <driverkit/return.h>
#import <mach/notify.h>
#import <string.h>
#import <syslog.h>

/* Private libDriver.A entry points used by Omni's original V2Server. */
extern IOReturn _IOGetDeviceConfig(port_t devicePort,
                                  unsigned int *interrupts,
                                  unsigned int *interruptCount,
                                  IORange *memoryRanges,
                                  unsigned int *memoryRangeCount);
extern IOReturn _IOMapDeviceMemory(port_t devicePort, port_t targetTask,
                                  vm_address_t physicalAddress,
                                  vm_size_t length,
                                  vm_address_t *mappedAddress,
                                  boolean_t findSpace, IOCache cacheMode);

/* Generated by MIG from the kernel protocol. */
extern kern_return_t V2Driver_ReadConfigLong(port_t, unsigned int,
                                             unsigned int, unsigned int *);
extern kern_return_t V2Driver_WriteConfigLong(port_t, unsigned int,
                                              unsigned int, unsigned int);

port_t V2KernelDriverPort = PORT_NULL;

static V2ServerDevice devices[V2SERVER_MAX_DEVICES];
static unsigned int deviceCount;
static struct mutex deviceMutex = MUTEX_INITIALIZER;

kern_return_t
V2ServerAddDevice(port_t devicePort)
{
    V2ServerDevice *device;
    unsigned int ioConfig[V2SERVER_QUERY_MAX_RANGES];
    IORange ranges[V2SERVER_QUERY_MAX_RANGES];
    unsigned int ioConfigCount = V2SERVER_QUERY_MAX_RANGES;
    unsigned int rangeCount = V2SERVER_QUERY_MAX_RANGES;
    unsigned int storedRangeCount;
    IOReturn result;

    if (devicePort == PORT_NULL || deviceCount >= V2SERVER_MAX_DEVICES)
        return KERN_INVALID_ARGUMENT;

    device = &devices[deviceCount];
    memset(device, 0, sizeof(*device));
    result = _IOGetDeviceConfig(devicePort, ioConfig, &ioConfigCount,
                                ranges, &rangeCount);
    if (result != IO_R_SUCCESS)
        return KERN_FAILURE;
    storedRangeCount = (rangeCount < V2SERVER_MAX_RANGES) ?
                       rangeCount : V2SERVER_MAX_RANGES;
    memcpy(device->ranges, ranges, storedRangeCount * sizeof(IORange));
    device->devicePort = devicePort;
    device->rangeCount = storedRangeCount;
    deviceCount++;
    return KERN_SUCCESS;
}

kern_return_t
V2Server_CountDevices(port_t serverPort, unsigned int *deviceCountOut)
{
    if (deviceCountOut == 0)
        return KERN_INVALID_ARGUMENT;
    *deviceCountOut = deviceCount;
    return KERN_SUCCESS;
}

kern_return_t
V2Server_ReadConfigLong(port_t serverPort, unsigned int deviceIndex,
                        unsigned int address, unsigned int *value)
{
    if (V2KernelDriverPort == PORT_NULL)
        return KERN_FAILURE;
    return V2Driver_ReadConfigLong(V2KernelDriverPort, deviceIndex,
                                   address, value);
}

kern_return_t
V2Server_WriteConfigLong(port_t serverPort, unsigned int deviceIndex,
                         unsigned int address, unsigned int value)
{
    if (V2KernelDriverPort == PORT_NULL)
        return KERN_FAILURE;
    return V2Driver_WriteConfigLong(V2KernelDriverPort, deviceIndex,
                                    address, value);
}

kern_return_t
V2Server_MapDeviceMemory(port_t serverPort, port_t targetTask,
                         unsigned int deviceIndex, vm_address_t *baseAddress,
                         vm_size_t *length, boolean_t resetOnDisconnect)
{
    V2ServerDevice *device;
    IORange range;
    vm_address_t mappedAddress = 0;
    vm_address_t pageBase;
    vm_address_t pageOffset;
    IOReturn result;

    if (targetTask == PORT_NULL || baseAddress == 0 || length == 0 ||
        deviceIndex >= deviceCount)
        return KERN_INVALID_ARGUMENT;

    mutex_lock(&deviceMutex);
    device = &devices[deviceIndex];
    if (device->ownerTask != PORT_NULL || device->rangeCount == 0) {
        mutex_unlock(&deviceMutex);
        return KERN_FAILURE;
    }

    range = device->ranges[0];
    pageOffset = range.start % vm_page_size;
    pageBase = range.start - pageOffset;
    result = _IOMapDeviceMemory(device->devicePort, targetTask, pageBase,
                                range.size, &mappedAddress, TRUE, IO_CacheOff);
    if (result == IO_R_SUCCESS) {
        device->ownerTask = targetTask;
        device->resetOnDisconnect = resetOnDisconnect;
        *baseAddress = (mappedAddress - (mappedAddress % vm_page_size)) +
                       pageOffset;
        *length = range.size;
    }
    mutex_unlock(&deviceMutex);
    return (result == IO_R_SUCCESS) ? KERN_SUCCESS : KERN_FAILURE;
}

void
V2ServerReleaseOwner(port_t ownerTask)
{
    unsigned int index;
    boolean_t reset = FALSE;

    mutex_lock(&deviceMutex);
    for (index = 0; index < deviceCount; index++) {
        if (devices[index].ownerTask == ownerTask) {
            devices[index].ownerTask = PORT_NULL;
            reset |= devices[index].resetOnDisconnect;
            devices[index].resetOnDisconnect = FALSE;
        }
    }
    mutex_unlock(&deviceMutex);

    if (reset)
        syslog(LOG_NOTICE,
               "V2Server: client exited; hardware reset awaits Glide port");
}

any_t
V2ServerCleanupThread(any_t argument)
{
    port_t notifyPort = (port_t)argument;
    notification_t notification;
    msg_return_t result;

    for (;;) {
        memset(&notification, 0, sizeof(notification));
        notification.notify_header.msg_size = sizeof(notification);
        notification.notify_header.msg_local_port = notifyPort;
        result = msg_receive(&notification.notify_header, MSG_OPTION_NONE, 0);
        if (result == RCV_SUCCESS &&
            notification.notify_header.msg_id == NOTIFY_PORT_DELETED)
            V2ServerReleaseOwner(notification.notify_port);
    }
    return 0;
}
