APP_NAME = ReopenStepWorkbench

ReopenStepWorkbench_OBJC_FILES = \
    main.m \
    RSCommandRunner.m \
    RSWorkbenchController.m

ReopenStepWorkbench_HEADER_FILES = \
    RSCommandRunner.h \
    RSWorkbenchController.h

ReopenStepWorkbench_RESOURCE_FILES = Info.plist

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make
